import * as vscode from "vscode";

export const MATERIALS_GUIDE_MD = [
  "# English Training: Bring Your Own Materials",
  "",
  "The extension reads daily lesson packages from a `prebuilt/` directory.",
  "Each lesson lives in its own `YYYY-MM-DD` folder.",
  "",
  "## Minimum directory layout",
  "",
  "```",
  "your-training-root/",
  "├── prebuilt/",
  "│   ├── 2026-05-10/",
  "│   │   ├── english-training.json   # required",
  "│   │   ├── manifest.json           # optional, declares generated assets",
  "│   │   ├── daily-card.png          # optional reading card image",
  "│   │   ├── prosody-detail.png      # optional stress/intonation card image",
  "│   │   └── audio/demo.ogg          # optional prebuilt reference audio",
  "│   ├── 2026-05-11/",
  "│   │   └── english-training.json",
  "│   └── ...",
  "└── progress/                        # auto-created by the extension",
  "```",
  "",
  "Point the extension at this root either way:",
  "",
  "- **Local**: open the parent folder as your VS Code workspace, OR set",
  "  `englishTraining.localMaterialsRoot` to its absolute path so the sidebar",
  "  works from any workspace.",
  "- In the sidebar, click **Local Folder** to choose or switch the local",
  "  materials root.",
  "",
  "The Practice sidebar's **Source Diagnostics** section shows the exact source",
  "mode, root folder, lesson count, current package date, and current",
  "`english-training.json` path.",
  "",
  "## Learner profile",
  "",
  "Add one optional profile file under the same materials root:",
  "",
  "```",
  "profile/learner-profile.md",
  "# or",
  "profile/learner-profile.json",
  "```",
  "",
  "When present, the sidebar shows **Profile loaded** and the coach receives the",
  "profile with each practice turn. Use it for research focus, speaking goals,",
  "common weaknesses, preferred feedback style, and terminology.",
  "",
  "## Required fields in `english-training.json`",
  "",
  "| Field | Type | Purpose |",
  "|-------|------|---------|",
  "| `date` | string `YYYY-MM-DD` | Must match the folder name. |",
  "| `scenario` | string | One-line context: who you're talking to, what they asked. |",
  "| `goal` | string | What a successful answer sounds like. |",
  "| `chinese_setup` | string | Chinese instruction shown to the learner. |",
  "| `frames` | array of `{label, text}` | Reusable spoken patterns. |",
  "| `clean_tts_text` | string | The native-version sentence used for TTS. |",
  "",
  "Useful optional fields: `training_type`, `primary_tags`, `demo_line`,",
  "`audio_text`, `stress_guide`, `intonation_guide`, `word_level_prosody`.",
  "",
  "## FSI drill package",
  "",
  "Add `followup-drill.json` beside `english-training.json` when the day should",
  "continue beyond one fixed sentence. The sidebar reads `rounds[].examples[]`",
  "and turns them into Listen / Practice / Skip choices.",
  "",
  "```json",
  "{",
  "  \"method\": \"FSI-style substitution + shadowing\",",
  "  \"rounds\": [",
  "    {",
  "      \"label\": \"Substitution: claim and example\",",
  "      \"base_frame\": \"My claim is that authorization should matter.\",",
  "      \"slot\": \"claim / example\",",
  "      \"examples\": [",
  "        { \"cue\": \"claim\", \"text\": \"My claim is that authorization should matter.\" },",
  "        { \"cue\": \"example\", \"text\": \"A concrete example is when a useful agent gets blocked.\" }",
  "      ]",
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "Coach responses may also include `drill_examples[]`; those generated examples",
  "are shown together with the prebuilt FSI lines after each practice result.",
  "",
  "## Reading-card and prosody contract",
  "",
  "When present, the Practice sidebar displays the generated reading cards and",
  "the structured prosody data for the current package.",
  "",
  "Default asset paths inside each package:",
  "",
  "| Asset | Default path | Manifest key |",
  "|-------|--------------|--------------|",
  "| Daily reading card | `daily-card.png` | `files.daily_card` |",
  "| Prosody detail card | `prosody-detail.png` | `files.prosody_detail` |",
  "| Prebuilt demo audio | `audio/demo.ogg` | `files.audio_demo` |",
  "| Audio generation queue | `audio-queue.json` | `files.audio_queue` |",
  "| Telegram card | `telegram-task-card.md` | `files.telegram_task_card` |",
  "",
  "Asset paths in `manifest.json` may be relative to the package folder or",
  "absolute paths. If `manifest.json` is missing, the sidebar falls back to the",
  "default paths above.",
  "",
  "Prosody fields expected by the sidebar:",
  "",
  "```json",
  "{",
  "  \"stress_guide\": \"The ˈBROADER ˈSIGNIFICANCE ...\",",
  "  \"intonation_guide\": \"Opening thought group. → | Final group. ↘\",",
  "  \"word_level_prosody\": {",
  "    \"groups\": [",
  "      { \"id\": 1, \"text\": \"Opening thought group.\", \"function\": \"statement\", \"nucleus\": \"group.\", \"contour\": \"→\", \"pause_after\": \"short\" }",
  "    ],",
  "    \"words\": [",
  "      { \"text\": \"Opening\", \"stress\": \"support\", \"pitch_role\": \"support beat\", \"arrow\": \"\", \"group\": 1 },",
  "      { \"text\": \"group.\", \"stress\": \"nucleus\", \"pitch_role\": \"falling target\", \"arrow\": \"↘\", \"group\": 1 }",
  "    ]",
  "  }",
  "}",
  "```",
  "",
  "## Quick start",
  "",
  "1. Open a workspace containing `prebuilt/`, or click **Local Folder** in the sidebar.",
  "2. Run `English Training: Create Sample Package` to write a starter file at",
  "   `prebuilt/<today>/english-training.json`.",
  "3. Edit that file: change `scenario`, `goal`, `frames`, `clean_tts_text`.",
  "4. Click `Refresh` in the sidebar — your lesson appears as the current task.",
  "5. Press the red record button and start practicing.",
  "",
  "## Multiple lessons / a curriculum",
  "",
  "Add one folder per day. The extension auto-walks `prebuilt/` for every",
  "`YYYY-MM-DD` directory and shows the 120-day heatmap from the dates it finds.",
  "There is no required curriculum length — 7 lessons or 365 lessons both work.",
  "",
  "## Example audio",
  "",
  "The sidebar does not require pre-generated OGG/MP3 files. Click",
  "**Generate Example** under *Example audio* to synthesize the example text on",
  "demand with your configured speech-output provider. It reads",
  "`clean_tts_text`, `audio_text`, or `demo_line` only; scenario, goal, and other",
  "background fields are never included in this reference audio.",
  "",
  "## Where session output goes",
  "",
  "- `<root>/runtime/vscode-sessions/<date>/<timestamp>/`.",
  "",
].join("\n");

export async function openMaterialsGuide(): Promise<void> {
  const doc = await vscode.workspace.openTextDocument({
    language: "markdown",
    content: MATERIALS_GUIDE_MD,
  });
  await vscode.window.showTextDocument(doc, { preview: false });
}
